modLoader="javafml"
loaderVersion="[40,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="minemention"
version="${file.jarVersion}"
displayName="Minemention"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minemention"
updateJSONURL="https://assets.melanx.de/updates/minemention.json"
authors="noeppi_noeppi"
description="""
"""

[[dependencies.minemention]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.1,)"
    ordering="NONE"
    side="BOTH"
